import XCTest
@testable import GarageHUDKit

/// The export must faithfully render recorded data — grouped parts, power, spend, assessment —
/// and invent nothing.
final class BuildSheetExporterTests: XCTestCase {

    private func s2k() -> Vehicle {
        var v = Vehicle(make: "Honda", model: "S2000", year: 2006, trim: "AP2", nickname: "S2K",
                        garageSlot: 1, factoryHorsepower: 237)
        v.drivetrain = .rwd
        v.documentedTotalInvestment = 12_396
        v.parts = [
            Part(name: "Supercharger", category: .forcedInduction, status: .installed, cost: 5760),
            Part(name: "ID1340s", category: .fueling, status: .installed, cost: 945),
            Part(name: "Koyo radiator", category: .cooling, status: .installed),
            Part(name: "Pistons", category: .engine, status: .installed, cost: 859),
            Part(name: "Clutch", category: .drivetrain, status: .installed),
            Part(name: "Planned BBK", category: .brakes, status: .wishlist, cost: 1800),
        ]
        v.performanceRecords = [PerformanceRecord(date: Date(timeIntervalSince1970: 1_700_000_000), type: .dyno, wheelHorsepower: 477)]
        v.buildEvents = [BuildEvent(date: Date(timeIntervalSince1970: 1_700_000_000), title: "Dyno tune — 477 whp")]
        return v
    }

    func testRendersKeySections() {
        let text = BuildSheetExporter.text(for: s2k())
        XCTAssertTrue(text.contains("2006 Honda S2000 AP2".uppercased()))
        XCTAssertTrue(text.contains("477 whp (measured)"))
        XCTAssertTrue(text.localizedCaseInsensitiveContains("$12,396 documented"))
        XCTAssertTrue(text.contains("Forced Induction:"))
        XCTAssertTrue(text.contains("- Supercharger — $5,760"))
        XCTAssertTrue(text.localizedCaseInsensitiveContains("PLANNED"))
        XCTAssertTrue(text.contains("Planned BBK"))
        XCTAssertTrue(text.localizedCaseInsensitiveContains("build assessment"))
        XCTAssertTrue(text.contains("Dyno tune — 477 whp"))
        XCTAssertTrue(text.hasSuffix("Generated by GarageHUD"))
    }

    func testMinimalVehicleDoesntCrashOrInvent() {
        let text = BuildSheetExporter.text(for: Vehicle(make: "Honda", model: "Civic", year: 2020, garageSlot: 1))
        XCTAssertTrue(text.contains("Not yet measured"))
        XCTAssertFalse(text.contains("Installed parts"))   // none → section omitted
    }
}
